### ISSUE TITLE
Use index template instead of template

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/logstash-output-opensearch#12]
Since ES 7.8, recommended option is to create template is using _index_template instead of _template. In order to keep compatibility with logstash-output-elasticsearch, we are using _template . We could address this problem in two following ways:
1. Check for min version, if < 8, use template, else index_template
2. Support _index_template starting from OpenSearch 1.0.0, since it is first release, we can start using _index_template.

**Comment by vamshin** [comment]
I think this is a great feature to have it part of OpenSearch output plugin and if possible we should enable it. Otherwise we could defer for OpenSearch2.0. Will keep an eye on community feedback :)

**Comment by deepdatta** [comment]
Added an option "legacy_template" which can be set to false to use the _index_template APIs. It's true by default and uses the _template API to keep the current default behavior. The option for version based setting was difficult since we have a mix of version numbers ranging from 1.x, 2.x and 7.x between OpenSearch and OpenDistro.
