### ISSUE TITLE
newest Logstash versions

### ISSUE THREAD

**Issue by tgueldner-mms** [opensearch-project/logstash-output-opensearch#149]
We are facing this issue https://github.com/elastic/logstash/issues/8480 which seems to be fixed in Logstash version 7.17.1.

The latest version of logstash-oss-with-opensearch-output-plugin I can found is 7.16.3 (https://hub.docker.com/r/opensearchproject/logstash-oss-with-opensearch-output-plugin/tags), published 4 months ago.

There are many logstash versions released already. 5 releases for 7.17.x and the new 8.x releases as well. 

What is your plan to catch up all these logstash releases? I would expect that your build pipelines will release the pre-built logstash-with-opensearch-output-plugin rigth after a new Logstash release comes out.

As an alternative we need to bundle this release by ourself.

**Comment by brijos** [comment]
@tgueldner-mms are you finding that the plugin is not working? I know of (an issue with 8.x clients)[https://github.com/opensearch-project/logstash-output-opensearch/issues/132] that we are looking into. I have not heard of breaking changes in Logstash which require an update to the output and input clients other than what I highlighted.

**Comment by tgueldner-mms** [comment]
Hi @brijos,
I don't mean the openseach-output-plugin. Maybe this is a misunderstanding. 
My question was related to the prebuild docker container which combines logstash and this output-plugin, you can find at: https://hub.docker.com/r/opensearchproject/logstash-oss-with-opensearch-output-plugin/tags
Deployed "By [opensearchproject](https://hub.docker.com/u/opensearchproject) • Updated 4 months ago
The Official Docker Image of Logstash with OpenSearch Output Plugin (https://opensearch.org/)"

Latest version of this image is 7.16.3 and we need to run newer Logstash docker container with opensearch-output-plugin (reason: see my first post).

As this image is deployed by opensearch I'm asking how the team want to handle updates of Logstash in future. The documentation still claims to use Docker + Logstash + Opensearch Output Plugin (https://opensearch.org/docs/latest/clients/logstash/index/#docker) which makes no sense if the image stucks in 7.16.2

I want to know if we should create this Docker image by ourself or if there are plans to catch up the missing Logstash releases.

Until now I couldn't find the corresponding Dockerfile which was used to build logstash-oss-with-opensearch-output-plugin.

**Comment by Jon-AtAWS** [comment]
Hi @tgueldner-mms,

Have you tried deploying Logstash 7.17.1 and then adding the logstash output plugin separately? That should work and get you moving forward. Please let us know if that doesn't work.

Jon

**Comment by nobletrout** [comment]
The opensearch documentation and downloads steers people towards downloading the version listed [here](https://opensearch.org/versions/opensearch-2-1-0.html) under ingest tools which is pinned at 7.16.3. There are many nice features in the latest version. If the guidance is to provide an opensearch plugin which needs to be installed, it would be nice to provide documentation and releases related to that instead of providing a bundled logstash pinned at an older version. This introduces bitrot, vulnerability growth, and encourages bad practices for deployment.

Could you either provide:
1. clear instructions on how to install the ruby gem/plugin using logstash specific tools
2. a supported and maintained image of logstash with the plugin
