### ISSUE TITLE
[BUG] Unable to get the a version of Logstash OSS with OpenSearch Output Plugin that is compatible with Opensearch v1.2.3

### ISSUE THREAD

**Issue by henslylim** [opensearch-project/logstash-output-opensearch#177]
**Describe the bug**
There is no way to download an old version of logstash OSS with opensearch output plugin from the website. I also do not see a logstash OSS project here.

**To Reproduce**
1. Go to [Logstash OSS with OpenSearch Output Plugin](https://opensearch.org/versions/opensearch-1-2-3.html#data-ingest)
2. Click on 'Download'
3. Logstash v8.4.0 with opensearch output plugin is downloaded:
https://artifacts.opensearch.org/logstash/logstash-oss-with-opensearch-output-plugin-8.4.0-linux-x64.tar.gz

**Expected behavior**
logstash v7.10.2 (or what is compatible with opensearch v1.2.3 is downloaded)

**Additional context**
Why is there no repository for logstash OSS with opensearch output plugin here in github?

**Comment by deepdatta** [comment]
Hi @henslylim thanks for your interest in the logstash-output-opensearch plugin. Currently the OpenSearch website only provides the download link for the latest version which includes fixes for known vulnerabilities and should be backward compatible with older OpenSearch versions. Let us know if you run into any compatibility issues with [logstash-oss-with-opensearch-output-plugin-8.4.0](https://artifacts.opensearch.org/logstash/logstash-oss-with-opensearch-output-plugin-8.4.0-linux-x64.tar.gz).
About your other question, `logstash-oss-with-opensearch-output-plugin` doesn't have a separate repository because its not a  separate piece of code. It's an artifact generated by installing the latest [opensearch-output-plugin](https://rubygems.org/gems/logstash-output-opensearch) on top of a [logstash-oss](https://artifacts.elastic.co/downloads/logstash/logstash-oss-8.4.0-linux-x86_64.tar.gz) artifact.

**Comment by henslylim** [comment]
Hi @deepdatta ,
Is there an installation link for an older version of logstash oss (v7.10.2) that has the plugin installed with it?

**Comment by deepdatta** [comment]
Hi @henslylim, please look at the files in https://github.com/opensearch-project/project-website/tree/main/_artifacts/logstash-oss-with-opensearch-output-plugin they have links to the tars for archived versions.
However as I mentioned earlier, we don't recommend using the older versions as they lack security patches that might introduce vulnerabilities in your sytem.
